name: flutter_meetup_brasil
description: Um ambiente para gerenciamento de evento para compartilhamento de
  conhecimentos e experiências para fortalecer o mercado de flutter no Brasil.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  url_launcher: ^6.1.3

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
